### ISSUE TITLE
game use?

### ISSUE THREAD

**Issue by Brian151** [fengari-lua/fengari-web#45]
honestly, probably the main reason someone would want to use lua on the web is either on the server back-end, or for game scripting...

any pointers how i might implement it in a game or game engine? i'd ideally not want to be interpreting the scripts every single time i call them, because the use cases for this would probably be giving objects customizable behavior, which means executing that code probably once per frame/update...

**Comment by catwell** [comment]
I tend to think you would probably not use Fengari for a web-based game. You can, but if you need a whole game engine you'll probably go the WSAM route now.

Maybe look at frameworks that already support this (e.g. https://defold.com)?

**Comment by Brian151** [comment]
well, the goal is to have web and stand-alone desktop versions. want to support custom content and would much rather not have random scripts running with potentially no control over what they can do.

web assembly right now doesn't appeal to me as much as it first did...

**Comment by giann** [comment]
Fengari is not really a good fit for gamedev unless you're really light on performance requirements.

**Comment by SacredDuckwhale** [comment]
One of the best use cases for Lua is scripting in general, while embedded in a larger application, and running it inside the browser isn't actually that far off conceptually. Mainly it's slower due due to the added overhead and occasionally cumbersome to use due to lack of APIs/documentation.

> any pointers how i might implement it in a game or game engine? i'd ideally not want to be interpreting the scripts every single time i call them, because the use cases for this would probably be giving objects customizable behavior, which means executing that code probably once per frame/update...

This statement confuses me. Would you execute the same code in JavaScript every frame and if so, how would that be different? Doesn't the real overhead come in when you must interface between the JavaScript VM and the Lua VM? At least that's the only scenario where I've had performance issues, and that was real-time parsing of (large amounts of) binary data which I simply do in JS now.

From what I understand, the scripts are loaded once just like .js scripts would be. But maybe I'm misunderstanding the issue? At least in my use case, 90-95% of the time is taken up by the rendering engine, which runs in pure JavaScript anyway. But of course I'm not making the next AAA game, so YMMV.

**Comment by Brian151** [comment]
something like that

yeah, the interfacing part is what concerns me. definitely won't be parsing files with it. mainly just altering the behavior of some pre-defined objects

that would be ideal. i just worry even if the scripts are permanently loaded that the overhead of doing
object > script > return
object > script > return
countless times would cause noticeable slowdown

**Comment by SacredDuckwhale** [comment]
Have you done any benchmarking? The way I understand it, the overhead of merely running the Lua VM (inside the JS VM) won't really be a problem. Everything else depends on your choice of technology, i.e. the game engine you're planning to interface with and the target platform's capabilities (mobile vs desktop etc).

Of course running Lua natively, especially offline and with LuaJIT would be faster, but if you manipulate Lua tables there shouldn't be an issue. If you need to access JS objects it really depends on the number of times you have to interface.

You could always try spinning up a prototype and see how it does.

**Comment by Brian151** [comment]
right now, it's purely in the theoretical/planning stage. engine will be fully custom, specific for re-making a certain flash game.

and native is part of the problem as it has to be integrated somehow, too. in theory, most objects won't be using scripts, so that could help. but i'd rather plan for and assume they ALL are. 

i probably will eventually. certainly won't build a full implementation if a benchmark performs poorly. irl lately has been a nightmare, it happens literally EVERY time i think i might be able to work on a project like this.
